#!/usr/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -N dipole&dipole_acceleration 
#PBS -j oe
#PBS -q xeon

echo $HOSTNAME

cd $PBS_O_WORKDIR


echo $vec$end
rm simulation_parametersf90.mod
make simulation_parametersf90
mpiexec -n 12 ./schrodinger1Df90
mpiexec -n 12 ./generateH0f90
mpiexec -n 12 ./generateH1f90
mpiexec -n 12 ./generateDipoleAccelerationf90
mpiexec -n 12 ./propagatef90

