#!/bin/bash
#SBATCH -J 20-1e14-800nm                # Job name
#SBATCH -N 2                  # Total number of nodes (16 cores/node)
#SBATCH -n 32               # Total number of tasks
#SBATCH --qos=normal
#SBATCH -p opteron                        # Queue name
#SBATCH -o run_%j.log          # Name of stdout output file (%j expands to jobid)
#SBATCH -t 1-00:00:00            # Run time (hh:mm:ss)
#SBATCH --mem=26G

mpirun -np 32 --host photon9,photon10 ./basisf90
